### ISSUE TITLE
我在初始化的时候，一直提示 No implementation found for jni.PusherNative.setAudioOptions(Native Method)

### ISSUE THREAD

**Issue by jiaojunjiahanlin** [EarthXiang/LivePublisher#12]
一直提示 No implementation found for jni.PusherNative.setAudioOptions(Native Method)
是否是so文件导入姿势不对
![image](https://cloud.githubusercontent.com/assets/8243962/16075140/2e5b3164-3320-11e6-9b3a-d6d7478ec976.png)

`06-15 17:30:31.125 26648-26648/com.qiniu.liuhanlin.live_publisher W/linker: /data/app/com.qiniu.liuhanlin.live_publisher-1/lib/arm/libPusher.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
06-15 17:30:31.147 26648-26648/com.qiniu.liuhanlin.live_publisher E/art: No implementation found for void com.qiniu.liuhanlin.live_publisher.jni.PusherNative.setAudioOptions(int, int) (tried Java_com_qiniu_liuhanlin_live_1publisher_jni_PusherNative_setAudioOptions and Java_com_qiniu_liuhanlin_live_1publisher_jni_PusherNative_setAudioOptions__II)
06-15 17:30:31.147 26648-26648/com.qiniu.liuhanlin.live_publisher D/AndroidRuntime: Shutting down VM
06-15 17:30:31.148 26648-26648/com.qiniu.liuhanlin.live_publisher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.qiniu.liuhanlin.live_publisher, PID: 26648
                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.qiniu.liuhanlin.live_publisher.jni.PusherNative.setAudioOptions(int, int) (tried Java_com_qiniu_liuhanlin_live_1publisher_jni_PusherNative_setAudioOptions and Java_com_qiniu_liuhanlin_live_1publisher_jni_PusherNative_setAudioOptions__II)
                                                                                        at com.qiniu.liuhanlin.live_publisher.jni.PusherNative.setAudioOptions(Native Method)
                                                                                        at com.qiniu.liuhanlin.live_publisher.pusher.AudioPusher.<init>(AudioPusher.java:27)
                                                                                        at com.qiniu.liuhanlin.live_publisher.LivePusher.prepare(LivePusher.java:39)
                                                                                        at com.qiniu.liuhanlin.live_publisher.MainActivity.onCreate(MainActivity.java:85)
                                                                                        at android.app.Activity.performCreate(Activity.java:6303)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5432)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
06-15 17:30:31.160 26648-26648/com.qiniu.liuhanlin.live_publisher I/Process: Sending signal. PID: 26648 SIG: 9
`
我将工程重新导入到了android studio中

**Comment by zhangle1** [comment]
我也出现了这个问题
